### ISSUE TITLE
Parse errors get sent to client

### ISSUE THREAD

**Issue by sproctor** [elanthia-online/lich-5#249]
I'll just paste my logs here:

```
[2022-07-11 12:26:55,669] <component id='room objs'>  You also see a granite altar with several candles and a water     jug on it, and a granite font.
 [2022-07-11 12:26:55,669] error: server_thread: Missing end tag for '/component'
 [2022-07-11 12:26:55,669] Line: 1
 [2022-07-11 12:26:55,669] Position: 122
 [2022-07-11 12:26:55,669] Last 80 unconsumed characters:
 [2022-07-11 12:26:55,670]
 [2022-07-11 12:26:55,670]   /home/sproctor/.gem/gems/rexml-3.2.5/lib/rexml/parsers/streamparser.rb:25:in `parse'
 [2022-07-11 12:26:55,670]   /home/sproctor/.gem/gems/rexml-3.2.5/lib/rexml/document.rb:402:in `parse_stream'
 [2022-07-11 12:26:55,670]   ./lich.rbw:2376:in `block in open'
 [2022-07-11 12:26:55,670] </component>
 [2022-07-11 12:26:55,671] error: server_thread: Unexpected top-level end tag (got 'component')
 [2022-07-11 12:26:55,671] Line: 1
 [2022-07-11 12:26:55,671] Position: 12
 [2022-07-11 12:26:55,671] Last 80 unconsumed characters:
 [2022-07-11 12:26:55,671]
 [2022-07-11 12:26:55,671]   /home/sproctor/.gem/gems/rexml-3.2.5/lib/rexml/parsers/baseparser.rb:360:in `pull_event'
 [2022-07-11 12:26:55,671]   /home/sproctor/.gem/gems/rexml-3.2.5/lib/rexml/parsers/baseparser.rb:183:in `pull'
 [2022-07-11 12:26:55,671]   /home/sproctor/.gem/gems/rexml-3.2.5/lib/rexml/parsers/streamparser.rb:20:in `parse'
 [2022-07-11 12:26:55,671]   /home/sproctor/.gem/gems/rexml-3.2.5/lib/rexml/document.rb:402:in `parse_stream'
 [2022-07-11 12:26:55,671]   ./lich.rbw:2376:in `block in open'
```

This should get sent to a log file or stderr, not to the client.

**Comment by MahtraDR** [comment]
This is sent to a log in lich/temp

In my PR for fixing janky XML it additionally logs exactly what line triggered the error. 

I also think this specific error would have been fix by that PR.

**Comment by mrhoribu** [comment]
Should be fixed with now merged PR. Closing.
