### ISSUE TITLE
stash.rb errors out when certain container inventory changes

### ISSUE THREAD

**Issue by HebrewToYou** [elanthia-online/lich-5#504]
**Steps to Reproduce:**

1. Establish a worn weapon container (e.g. `a sheath`)
2. Using READY/STORE functionality, set your `weapon` and `sheath` values to the applicable items
3. Log out
4. Log in
5. Remove the weapon container and replace it with a different container noun (e.g. `a harness`)
6. Update the READY/STORE functionality to set the new weapon container as your `sheath` location
7. GIRD your weapon and shield (or two weapons - you just need to have both hands filled)
8. Execute `;eherbs`

**Expected Result:**

The right hand weapon is stored properly in its sheath location and the script functions as expected

**Actual Result**

```>;eherbs
--- Lich: error: could not find Container[name: sheath]
    /home/REDACTED/lich-5/lib/stash.rb:30:in `find_container'
    /home/REDACTED/lich-5/lib/stash.rb:35:in `container'
--- Lich: eherbs has exited.```

**Comment by HebrewToYou** [comment]
The issue resolves itself, by the way, if you log out and log back in.
